apiVersion: v1
kind: Service
metadata:
  name: helloworld-service1
spec:
  ports:
  - port: 80
    targetPort: nodejs-port
    protocol: TCP
  selector:
    app: helloworld-neeraj1
  type: LoadBalancer
