apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: neeraj-deployment
spec:
  selector:
    matchLabels:
      app: neeraj-hello-world
  replicas: 3 # tells deployment to run 2 pods matching the template
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1				  
  template:
    metadata:
      labels:
        app: neeraj-hello-world
    spec:
      containers:
      - name: neeraj-hello-world
        image: neerajd2/cloudsecops:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
