apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: helloworld-neeraj
spec:
  selector:
    matchLabels:
      app: helloworld-neeraj
  replicas: 3 # tells deployment to run 2 pods matching the template
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1				  
  template:
    metadata:
      labels:
        app: helloworld-neeraj
    spec:
      containers:
      - name: helloworld-neeraj
        image: neerajd2/cloudsecops:071be8f066722b31be5ec2206bed41fdfe2cc499
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
